# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Iho Somnam
subtitle: Science will reveal the truth.
description: Here you can find me publicly social connection. # this means to ignore newlines until "baseurl:" Leave it! Cause I use HTML FUCKER!
social:
  Instagram: gentiana_siva
  Twitter: iho4741
  Reddit: TheCureliestWalk883
  Github: iho4741
  Steam: TheCureliestWalk
  Keybase: iho4741
  Email: mail@ihosomnam.me
author: Iho Somnam
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-107485569-9
lang: en

# Build settings
markdown: kramdown
highlighter: rouge
show_excerpts: false
plugins:
  - jekyll-feed
